### ISSUE TITLE
Cleanup work here

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/hocr-tools#15]
After the update of the official repo, we can now cleanup our local repo a little:
- @kba Can we delete the branch https://github.com/UB-Mannheim/hocr-tools/tree/readme-update ?
- I updated the master branch here now. I suggest to switch the default branch here back to the master branch.
- Maybe some time later we should also delete the `new` branch completely (but for the moment I suggest to keep that for possible links to it).
- Anything else?

**Comment by kba** [comment]
> @kba Can we delete the branch https://github.com/UB-Mannheim/hocr-tools/tree/readme-update ?

Yes and done.

> I updated the master branch here now. I suggest to switch the default branch here back to the master branch.

Yes and done.

> Maybe some time later we should also delete the new branch completely (but for the moment I suggest to keep that for possible links to it).

Okay, but I think it's safe to delete it. Requires a bit of work for pull requests but not much (`s/new/master/g` in `.git/config`).

I closed the obsolete issues here.

**Comment by zuphilip** [comment]
Deleting `new` branch is fine for me. (I type the branch explicit in the git dash or can choose it from a drop-down in Tortoise-Git. Thus, no difference for me at all.)
