### ISSUE TITLE
[hocr-extract-images] Fix/Relax finding the link to the image

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/hocr-tools#2]
Currently the hocr-extract-images script tries to find the image as an attribute of the form

```
title='file 417576986_0027.bin.png
```

but it should also allow the form

```
title='image "417576986_0027.bin.png"
```

Thus, we should also check for the parameter `image` besides `file` and moreover strip all quotation signs.

**Comment by stweil** [comment]
This is implemented by commit 84471417f6604e03042e0f35d7ac8d7f95e289c5.

**Comment by stweil** [comment]
@zuphilip, the current `new` branch with my commit works for me. As soon as you have confirmed that it solves this issue, we can close it.

**Comment by zuphilip** [comment]
Yes, works fine. Thank you!
