### ISSUE TITLE
[ocropus-gtedit] title attribute should not be capitalize-first

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/hocr-tools#3]
The generated HTML makes the first letter of the title of the HTML a capital, which makes the browser propose the wrong file name for "Save Page as"

**Comment by zuphilip** [comment]
Okay, that script is part of the `ocropy` repository.

**Comment by kba** [comment]
Yes, I'm aware of that, just wanted to jot it down quickly so I wouldn't forget :)

**Comment by kba** [comment]
https://github.com/tmbdev/ocropy/pull/85
