### ISSUE TITLE
Provide installation scripts / packages

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/hocr-tools#4]
Currently these Python scripts can only be called by referencing directly. How can we register them to make a call possible system-wide?

**Comment by stweil** [comment]
I am not sure whether I have understood your question, but maybe you have these options:
- Copy or link them to a directory which is in your `PATH`?
- Create a Debian installer?

**Comment by kba** [comment]
These are all self-contained (beyond deps on modules), so copying them to `~/bin` should work. Packaging them is also possible, https://github.com/jordansissel/fpm makes this very easy for a simple binary-only deb package.

**Comment by zuphilip** [comment]
Yeah, I guess I am thinking about something similar than the [ocropy/setup.py](https://github.com/tmbdev/ocropy/blob/master/setup.py). Is the python `setup` command making the magic here? @kba I don't know packaging...

**Comment by stweil** [comment]
Ah, it looks like ocropy uses some kind of standard how Python scripts can be registered. Yes, that might be a good approach for the hocr-tools, too.

Nowadays, several major script language provide their own "packaging" and registration methods.

In contrast to this language specific packaging, Linux distributions also provide packages of preconfigured software functionality. The tool suggested by @kba allows creating such packages.

**Comment by kba** [comment]
I'm setting up hocr-tools to use setuptools, so it can be installed with the python toolchain.

**Comment by stweil** [comment]
Is this related: https://docs.python.org/2/tutorial/modules.html#packages ?

**Comment by kba** [comment]
@stweil Python packaging is usually done using [distutils](https://docs.python.org/2.7//distutils/index.html). First PR for this is here: https://github.com/UB-Mannheim/hocr-tools/pull/5

**Comment by stweil** [comment]
Yes, I noticed that PR. `pylint hocr_tools` looks for a file named `hocr_tools/__init__.py` which is related to Pythons modules / packages, but which is not part of your PR.

**Comment by kba** [comment]
It's not a python module, so there's no `__init__.py`. This is just about installing requirements and setting up scripts in the $PATH.

**Comment by zuphilip** [comment]
@kba @stweil Can we close this issue?

**Comment by kba** [comment]
I think #5 should fix this, `sudo python setup.py install` should be enough now to install it. :+1: for closing.
