### ISSUE TITLE
Document status of the scripts

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/hocr-tools#8]
Some scripts should be running fine, e.g. `extract-images`, others are probably not up-to-date/very specific.

The `eval-*` scripts require pylab (which has a lot of dependencies).

The dependencies on `xml.dom.ext.reader` should be ported to lxml.

~~`hocr-pdf` requires reportlab, should be added to requirements.~~

**Comment by zuphilip** [comment]
@kba Is this equivalent to the other commits which aim to change to use `lxml`? If not please make a new issue at https://github.com/tmbdev/hocr-tools/issues . We should close the issues here in our fork and concentrate on the official fork.

**Comment by kba** [comment]
I think this can be closed. I'd love to see some usage examples/test data for the hocr-eval\* scripts but they should work now. Other than that, lxml porting is the remaining issue here and that is tracked by https://github.com/tmbdev/hocr-tools/issues/8
